In [4]:
import numpy as np
lst1 = [1,2,3,4,5]
lst2 = [5,4,3,2,1]
np1 = np.array(lst1)
np1 * 2

array([ 2,  4,  6,  8, 10])

In [5]:
np2 = np.array(lst2)
sum_np = np1 + np2
sum_np

array([6, 6, 6, 6, 6])

In [6]:
lst3 = ['a', 'b', 'c', 'd', 'e']
lst4 = [1, 'a', 2, 'b', 3, 'c', 4]
print(lst3)
print(lst4)

['a', 'b', 'c', 'd', 'e']
[1, 'a', 2, 'b', 3, 'c', 4]


In [8]:
item_price = [1000, 2000, 2500, 3000]
np_price = np.array(item_price)
np_new_price = np_price * 1.1
print(np_new_price)

[1100. 2200. 2750. 3300.]


In [9]:
mid = np.array([70,90,80,100])
fin = np.array([90, 60, 90, 100])
avg = (mid + fin) / 2
avg

array([ 80.,  75.,  85., 100.])

In [12]:
n = np.array([1,2,3,4,5])
print(n.ndim)
print(n.shape)
print(n.size)
print(n.itemsize)
print(n.dtype)

1
(5,)
5
8
int64
